{"timestamp":"2025-08-17T20:38:36.153906","level":"info","event":"DAG bundles loaded: dags-folder","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-17T20:38:36.180472","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/etl_process.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-17T20:38:39.625126","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T20:38:40.162639","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T20:38:41.070386","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T20:38:41.246660","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T20:38:41.372710","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T20:38:41.436734","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T20:38:41.897635","level":"warning","event":"/home/airflow/.local/lib/python3.12/site-packages/sklearn/preprocessing/_encoders.py:228: UserWarning: Found unknown categories in columns [0] during transform. These unknown categories will be encoded as all zeros\n  warnings.warn(\n","logger":"py.warnings"}
{"timestamp":"2025-08-17T20:38:54.106158","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T20:38:54.336183","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T20:38:56.334647","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T20:38:56.432665","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T20:38:56.486834","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T20:38:56.580115","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T20:38:57.061406","level":"info","event":"Found credentials in environment variables.","logger":"botocore.credentials"}
{"timestamp":"2025-08-17T20:38:57.130874","level":"info","event":"Found endpoint for s3 via: environment_service.","logger":"botocore.configprovider"}
{"timestamp":"2025-08-17T20:38:58.641727Z","level":"error","event":"2025/08/17 20:38:58 WARNING mlflow.models.model: `artifact_path` is deprecated. Please use `name` instead.","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-17T20:38:59.161636Z","level":"error","event":"2025/08/17 20:38:59 WARNING mlflow.sklearn: Model was missing function: predict. Not logging python_function flavor!","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-17T20:39:11.978324Z","level":"error","event":"\u001b[31m2025/08/17 20:39:11 WARNING mlflow.models.model: Model logged without a signature and input example. Please set `input_example` parameter when logging the model to auto infer the model signature.\u001b[0m","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-17T20:39:12.537907Z","level":"info","event":"üèÉ View run ETL_run_2025/08/17-18:09:04\" at: http://mlflow:5000/#/experiments/1/runs/534b67d1c3e84f6887fe544839b97ac0","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-17T20:39:12.538341Z","level":"info","event":"üß™ View experiment at: http://mlflow:5000/#/experiments/1","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-17T20:39:12.614816","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"MlflowException","exc_value":"INVALID_PARAMETER_VALUE: Changing param values is not allowed. Param with key='Train observations' was already logged with value='22113' for run ID='534b67d1c3e84f6887fe544839b97ac0'. Attempted logging new value '35490'.\n\nThe cause of this error is typically due to repeated calls\nto an individual run_id event logging.\n\nIncorrect Example:\n---------------------------------------\nwith mlflow.start_run():\n    mlflow.log_param(\"depth\", 3)\n    mlflow.log_param(\"depth\", 5)\n---------------------------------------\n\nWhich will throw an MlflowException for overwriting a\nlogged parameter.\n\nCorrect Example:\n---------------------------------------\nwith mlflow.start_run():\n    with mlflow.start_run(nested=True):\n        mlflow.log_param(\"depth\", 3)\n    with mlflow.start_run(nested=True):\n        mlflow.log_param(\"depth\", 5)\n---------------------------------------\n\nWhich will create a new nested run for each individual\nmodel and prevent parameter key collisions within the\ntracking store.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":867,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1159,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/decorator.py","lineno":251,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":216,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":239,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/etl_process.py","lineno":463,"name":"encode_normalize_features"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/fluent.py","lineno":775,"name":"log_param"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/client.py","lineno":2075,"name":"log_param"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py","lineno":397,"name":"log_param"}],"is_group":false,"exceptions":[]},{"exc_type":"RestException","exc_value":"INVALID_PARAMETER_VALUE: Changing param values is not allowed. Param with key='Train observations' was already logged with value='22113' for run ID='534b67d1c3e84f6887fe544839b97ac0'. Attempted logging new value '35490'.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/tracking/_tracking_service/client.py","lineno":390,"name":"log_param"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py","lineno":643,"name":"log_param"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/store/tracking/rest_store.py","lineno":133,"name":"_call_endpoint"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/utils/rest_utils.py","lineno":553,"name":"call_endpoint"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/mlflow/utils/rest_utils.py","lineno":308,"name":"verify_rest_response"}],"is_group":false,"exceptions":[]}]}
